services:
  - type: web
    name: pixelfly-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py wsgi:application
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: GOOGLE_API_KEY
        sync: false  # This should be set manually in Render dashboard
    autoDeploy: true
    disk:
      name: pixelfly-data
      mountPath: /opt/render/project/data
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 3
    region: oregon
